# --- Build Stage ---
FROM node:22-alpine AS builder

WORKDIR /usr/src/app

COPY server/package*.json ./

RUN npm ci --only=production

COPY server/src ./src

# --- Production Stage ---
FROM node:22-alpine

WORKDIR /usr/src/app

# Pre-create logs folder and transfer ownership to node user
RUN mkdir -p logs && chown -R node:node /usr/src/app

COPY --chown=node:node --from=builder /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=builder /usr/src/app/package*.json ./
COPY --chown=node:node --from=builder /usr/src/app/src ./src

USER node

EXPOSE 5000

ENV NODE_ENV=production
ENV PORT=5000

CMD ["node", "src/server.js"]
